#生活服务分类表
CREATE TABLE o2o_category(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  name VARCHAR(50) NOT NULL DEFAULT '',
  parent_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  KEY parent_id(`parent_id`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

#城市表
CREATE TABLE o2o_city(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  name VARCHAR(50) NOT NULL DEFAULT '',
  uname VARCHAR(50) NOT NULL DEFAULT '',
  parent_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  KEY parent_id(`parent_id`),
  UNIQUE KEY uname(`uname`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT o2o_city(name, uname, parent_id, is_default, status)
VALUES('常德', 'changde', 7, 0, 1);

#商圈表
CREATE TABLE o2o_area(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  name VARCHAR(50) NOT NULL DEFAULT '',
  city_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  parent_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  KEY parent_id(`parent_id`),
  KEY city_id(`city_id`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

#商户表
CREATE TABLE o2o_bis(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  name VARCHAR(50) NOT NULL DEFAULT '',
  email VARCHAR(50) NOT NULL DEFAULT '',
  logo VARCHAR(255) NOT NULL DEFAULT '',
  lisence_logo VARCHAR(255) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  city_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  city_path VARCHAR(50) NOT NULL DEFAULT '',
  bank_info VARCHAR(50) NOT NULL DEFAULT '',
  money DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  bank_name VARCHAR(50) NOT NULL DEFAULT '',
  bank_user VARCHAR(50) NOT NULL DEFAULT '',
  owner VARCHAR(20) NOT NULL DEFAULT '',
  owner_tel VARCHAR(20) NOT NULL DEFAULT '',
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  KEY name(`name`),
  KEY city_id(`city_id`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

#商户账号表
CREATE TABLE o2o_bis_account(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  username VARCHAR(50) NOT NULL DEFAULT '',
  password CHAR(32) NOT NULL DEFAULT '',
  code VARCHAR(10) NOT NULL DEFAULT '',
  bis_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  last_login_ip VARCHAR(20) NOT NULL DEFAULT '',
  last_login DATETIME NOT NULL DEFAULT now(),
  is_main TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  KEY bis_id(`bis_id`),
  KEY username(`username`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


#商户门店表
CREATE TABLE o2o_bis_location(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  name VARCHAR(50) NOT NULL DEFAULT '',
  logo VARCHAR(255) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL DEFAULT '',
  tel VARCHAR(20) NOT NULL DEFAULT '',
  contact VARCHAR(20) NOT NULL DEFAULT '',
  xpoint VARCHAR(20) NOT NULL DEFAULT '',
  ypoint VARCHAR(20) NOT NULL DEFAULT '',
  bis_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  open_time DATETIME NOT NULL DEFAULT now(),
  content TEXT NOT NULL,
  is_main TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  api_address VARCHAR(255) NOT NULL DEFAULT '',
  city_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  city_path VARCHAR(50) NOT NULL DEFAULT '',
  category_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  category_path VARCHAR(50) NOT NULL DEFAULT '',
  bank_info VARCHAR(50) NOT NULL DEFAULT '',
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  KEY name(`name`),
  KEY city_id(`city_id`),
  KEY bis_id(`bis_id`),
  KEY category_id(`category_id`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE o2o_bis_location
MODIFY open_time VARCHAR(50) NOT NULL DEFAULT '';

#团购商品表
CREATE TABLE o2o_deal(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  name VARCHAR(100) NOT NULL DEFAULT '',
  category_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  se_category_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  bis_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  location_ids VARCHAR(100) NOT NULL DEFAULT '',
  image VARCHAR(200) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  start_time DATETIME NOT NULL DEFAULT now(),
  end_time DATETIME NOT NULL DEFAULT now(),
  origin_price DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  current_price DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  city_id INT(11) UNSIGNED NOT NULL DEFAULT 0,
  buy_count INT(11) UNSIGNED NOT NULL DEFAULT 0,
  ttotal_count INT(11) UNSIGNED NOT NULL DEFAULT 0,
  coupins_begin_time DATETIME NOT NULL DEFAULT now(),
  coupons_end_time DATETIME NOT NULL DEFAULT now(),
  xpoint VARCHAR(20) NOT NULL DEFAULT '',
  ypoint VARCHAR(20) NOT NULL DEFAULT '',
  bis_account_id INT(10) UNSIGNED NOT NULL DEFAULT 0,
  balance_price DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  notes TEXT NOT NULL,
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  KEY name(`name`),
  KEY category_id(`category_id`),
  KEY se_category_id(`se_category_id`),
  KEY city_id(`city_id`),
  KEY start_time(`start_time`),
  KEY end_time(`end_time`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE o2o_deal
CHANGE coupins_begin_time coupons_begin_time DATETIME NOT NULL DEFAULT now();

ALTER TABLE o2o_deal
ADD se_city_id INT(11) UNSIGNED NOT NULL DEFAULT 0;

#前台用户表
CREATE TABLE o2o_user(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  username VARCHAR(100) NOT NULL DEFAULT '',
  password CHAR(32) NOT NULL DEFAULT '',
  code VARCHAR(10) NOT NULL DEFAULT '',
  last_login_ip VARCHAR(20) NOT NULL DEFAULT '',
  last_login DATETIME NOT NULL DEFAULT now(),
  email VARCHAR(50) NOT NULL DEFAULT '',
  tel VARCHAR(20) NOT NULL DEFAULT '',
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now(),
  UNIQUE KEY username(`username`),
  UNIQUE KEY email(`email`)
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


#推荐位表
CREATE TABLE o2o_featured(
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT KEY,
  type TINYINT(1) NOT NULL DEFAULT 0,
  title VARCHAR(30) NOT NULL DEFAULT '',
  image VARCHAR(255) NOT NULL DEFAULT '',
  url VARCHAR(255) NOT NULL DEFAULT '',
  description VARCHAR(255) NOT NULL DEFAULT '',
  listorder INT(8) UNSIGNED NOT NULL DEFAULT 0,
  status TINYINT(1) NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT now(),
  update_time DATETIME NOT NULL DEFAULT now()
)ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


ALTER TABLE o2o_city
MODIFY is_default TINYINT(1) NOT NULL DEFAULT 0 AFTER parent_id;



